version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - e2e-test
    depends_on:
      - postgres14-encryption

  postgres14-encryption:
    image: postgres:14
    container_name: postgres14-encryption
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres-encrypted'
      POSTGRES_DB: 'e2epoc'
    networks:
      - e2e-test

networks:
  e2e-test:
    driver: bridge
